namespacePrefixes:                       # namespace prefixes to be used in the result framing
  adms: http://www.w3.org/ns/adms#
  dcat: http://www.w3.org/ns/dcat#
  dcatap: http://data.europa.eu/r5r/
  dct: http://purl.org/dc/terms/
  eli: http://data.europa.eu/eli/ontology#
  foaf: http://xmlns.com/foaf/0.1/
  locn: http://www.w3.org/ns/locn#
  odrl: http://www.w3.org/ns/odrl/2/
  prov: http://www.w3.org/ns/prov#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sh: http://www.w3.org/ns/shacl#
  skos: http://www.w3.org/2004/02/skos/core#
  spdx: http://spdx.org/rdf/terms#
  time: http://www.w3.org/2006/time#
  vcard: http://www.w3.org/2006/vcard/ns#
  xsd: http://www.w3.org/2001/XMLSchema#

dataSources:
  nodeShapes:                             # name of the data source
    resolver: sparql                      # indicates the SPARQL resolver type
    location: sparql/nodeShapes.rq        # location of the SPARQL query
    source:                               # source of the data to be queried
      - /shapes/dcat-ap-SHACL.ttl
      - /shapes/dcat-ap-OPT.ttl
      - /shapes/dcat-ap-nl-SHACL.ttl
      - /shapes/dcat-ap-nl-OPT.ttl
      - /shapes/optionaliteit.ttl
    resultFrame:                          # frame to be used for the result  
      _key: targetClass                   # key with which a node is identified
      targetClass:                        # target class property of the node        
        _value: targetClass               # value of the target class property from the SPARQL query
        _prefix: true                     # indicates that the value should be prefixed using the namespace prefixes
      propertyShapes:                     # property shapes property of the node
        _key: property                    # key with which a property shape is identified
        _orderBy: +propertyName           # order the property shapes by the value of its propertyName property. + indcates ascending order.  
        propertyName: propertyName        # property name property of the property shape
        property: property                # property property of the property shape
        propertyPrefixed:                 # prefixed property property of the property shape
          _value: property
          _prefix: true
        description: description          # description property of the property shape
        class: class                      # class property of the property shape
        classPrefixed:                    # prefixed class property of the property shape
          _value: class
          _prefix: true
        datatype: datatype                # datatype property of the property shape
        datatypePrefixed:                 # prefixed datatype property of the property shape
          _value: datatype
          _prefix: true
        nodeKind: nodeKind                # node kind property of the property shape
        nodeKindPrefixed:                 # prefixed node kind property of the property shape
          _value: nodeKind
          _prefix: true
        minCount: minCount                # min count property of the property shape
        maxCount: maxCount                # max count property of the property shape
        optionaliteit:                    # optionaliteit property of the property shape
          _value: optionaliteit
          _type: set                      # indicates that the value should be treated as a set

templates:                                # List of templates to be used for generating the documentation
  - templateLocation: klassen.md          # location of the template 
    outputLocation: /doc/gen/             # location where the templated results should be stored
  - templateLocation: ondersteunendeKlassen.md
    outputLocation: /doc/gen/
